### ISSUE TITLE
mod_bunny and bunny should support multi amqp broker definition  

### ISSUE THREAD

**Issue by rvrignaud** [cloudwatt/mod_bunny#1]
Hello,

IMHO we should be able to define multiple amqp broker to have a built-in failover method in mod_bunny.
I know we could use haproxy in front of a rabbitmq cluster but I'd prefer to have the smallest infrastructure dependency as possible in my monitoring solution.

Cheers,

Romain

**Comment by falzm** [comment]
Hi

I see your point. However implementing multi-endpoints support is a big chunk of work, and I don't think I would do it more efficiently than a proper load-balancer/high availability device would do. Besides, if you already have a clustered RabbitMQ setup then your monitoring infrastructure isn't _that_ small, and I would strongly recommend you to put a software LB — HAproxy + keepalived is a good fit for that — in front of your RabbitMQ cluster, because most AMQP clients don't handle multi-endpoints brokers.

m.
