### ISSUE TITLE
Mod_bunny doesn't respect the service_check_timeout

### ISSUE THREAD

**Issue by rvrignaud** [cloudwatt/mod_bunny#3]
When scheduling service checks and never getting any anwser (with no bunny-worker running for instance), mod_bunny does not apply any service timeout.
In "plain nagios", if service timeout, the service state is set to Critical.

**Comment by falzm** [comment]
Hello

Check timeout (execution time took longer than allowed time, but the check results is still sent back to Nagios) is not the same as "orphaned" check (the check has not been executed or its result never made it back to Nagios).

Check timeout is already handled by the worker, however the "orphaned" checks weren't: this bug has been fixed in commit f027fe607965fbdb611c848e0223283143571804 and release in version 0.4.0.

m.
